// Built using externs generator
// Step 1: Load https://cdnjs.cloudflare.com/ajax/libs/react/15.3.0/react.js
// Step 2: Load <built js from target dir>
// Use js namespace "ReactDateRange"
/**********************************************************************
 * Extern for ReactDateRange
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var ReactDateRange = {
  "Calendar": {
    "defaultProps": {
      "ariaLabels": {},
      "calendarFocus": {},
      "classNames": {},
      "color": {},
      "dateDisplayFormat": {},
      "dayDisplayFormat": {},
      "direction": {},
      "disabledDates": {},
      "disabledDay": function () {},
      "displayMode": {},
      "dragSelectionEnabled": {},
      "editableDateInputs": {},
      "endDatePlaceholder": {},
      "fixedHeight": {},
      "focusedRange": {},
      "locale": {
        "code": {},
        "formatDistance": function () {},
        "formatLong": {
          "date": function () {},
          "dateTime": function () {},
          "time": function () {}
        },
        "formatRelative": function () {},
        "localize": {
          "day": function () {},
          "dayPeriod": function () {},
          "era": function () {},
          "month": function () {},
          "ordinalNumber": function () {},
          "quarter": function () {}
        },
        "match": {
          "day": function () {},
          "dayPeriod": function () {},
          "era": function () {},
          "month": function () {},
          "ordinalNumber": function () {},
          "quarter": function () {}
        },
        "options": {
          "firstWeekContainsDate": {},
          "weekStartsOn": {}
        }
      },
      "maxDate": {},
      "minDate": {},
      "monthDisplayFormat": {},
      "months": {},
      "preventSnapRefocus": {},
      "rangeColors": {},
      "ranges": {},
      "scroll": {
        "enabled": {}
      },
      "showDateDisplay": {},
      "showMonthAndYearPickers": {},
      "showMonthArrow": {},
      "showPreview": {},
      "startDatePlaceholder": {},
      "weekdayDisplayFormat": {}
    },
    "propTypes": {
      "ariaLabels": {
        "isRequired": function () {}
      },
      "calendarFocus": {
        "isRequired": function () {}
      },
      "className": {
        "isRequired": function () {}
      },
      "classNames": {
        "isRequired": function () {}
      },
      "color": {
        "isRequired": function () {}
      },
      "date": {
        "isRequired": function () {}
      },
      "dateDisplayFormat": {
        "isRequired": function () {}
      },
      "dayDisplayFormat": {
        "isRequired": function () {}
      },
      "direction": {
        "isRequired": function () {}
      },
      "disabledDates": {
        "isRequired": function () {}
      },
      "disabledDay": {
        "isRequired": function () {}
      },
      "displayMode": {
        "isRequired": function () {}
      },
      "dragSelectionEnabled": {
        "isRequired": function () {}
      },
      "editableDateInputs": {
        "isRequired": function () {}
      },
      "endDatePlaceholder": {
        "isRequired": function () {}
      },
      "fixedHeight": {
        "isRequired": function () {}
      },
      "focusedRange": {
        "isRequired": function () {}
      },
      "initialFocusedRange": {
        "isRequired": function () {}
      },
      "locale": {
        "isRequired": function () {}
      },
      "maxDate": {
        "isRequired": function () {}
      },
      "minDate": {
        "isRequired": function () {}
      },
      "monthDisplayFormat": {
        "isRequired": function () {}
      },
      "months": {
        "isRequired": function () {}
      },
      "navigatorRenderer": {
        "isRequired": function () {}
      },
      "onChange": {
        "isRequired": function () {}
      },
      "onPreviewChange": {
        "isRequired": function () {}
      },
      "onRangeFocusChange": {
        "isRequired": function () {}
      },
      "onShownDateChange": {
        "isRequired": function () {}
      },
      "preventSnapRefocus": {
        "isRequired": function () {}
      },
      "preview": {
        "isRequired": function () {}
      },
      "rangeColors": {
        "isRequired": function () {}
      },
      "ranges": {
        "isRequired": function () {}
      },
      "scroll": {
        "isRequired": function () {}
      },
      "showDateDisplay": {
        "isRequired": function () {}
      },
      "showMonthAndYearPickers": {
        "isRequired": function () {}
      },
      "showMonthArrow": {
        "isRequired": function () {}
      },
      "showPreview": {
        "isRequired": function () {}
      },
      "shownDate": {
        "isRequired": function () {}
      },
      "startDatePlaceholder": {
        "isRequired": function () {}
      },
      "updateRange": {
        "isRequired": function () {}
      },
      "weekStartsOn": {
        "isRequired": function () {}
      },
      "weekdayDisplayFormat": {
        "isRequired": function () {}
      }
    }
  },
  "DateRange": {
    "defaultProps": {
      "classNames": {},
      "disabledDates": {},
      "moveRangeOnFirstSelection": {},
      "rangeColors": {},
      "ranges": {},
      "retainEndDateOnFirstSelection": {}
    },
    "propTypes": {
      "ariaLabels": {
        "isRequired": function () {}
      },
      "calendarFocus": {
        "isRequired": function () {}
      },
      "className": {
        "isRequired": function () {}
      },
      "classNames": {
        "isRequired": function () {}
      },
      "color": {
        "isRequired": function () {}
      },
      "date": {
        "isRequired": function () {}
      },
      "dateDisplayFormat": {
        "isRequired": function () {}
      },
      "dayDisplayFormat": {
        "isRequired": function () {}
      },
      "direction": {
        "isRequired": function () {}
      },
      "disabledDates": {
        "isRequired": function () {}
      },
      "disabledDay": {
        "isRequired": function () {}
      },
      "displayMode": {
        "isRequired": function () {}
      },
      "dragSelectionEnabled": {
        "isRequired": function () {}
      },
      "editableDateInputs": {
        "isRequired": function () {}
      },
      "endDatePlaceholder": {
        "isRequired": function () {}
      },
      "fixedHeight": {
        "isRequired": function () {}
      },
      "focusedRange": {
        "isRequired": function () {}
      },
      "initialFocusedRange": {
        "isRequired": function () {}
      },
      "locale": {
        "isRequired": function () {}
      },
      "maxDate": {
        "isRequired": function () {}
      },
      "minDate": {
        "isRequired": function () {}
      },
      "monthDisplayFormat": {
        "isRequired": function () {}
      },
      "months": {
        "isRequired": function () {}
      },
      "moveRangeOnFirstSelection": {
        "isRequired": function () {}
      },
      "navigatorRenderer": {
        "isRequired": function () {}
      },
      "onChange": {
        "isRequired": function () {}
      },
      "onPreviewChange": {
        "isRequired": function () {}
      },
      "onRangeFocusChange": {
        "isRequired": function () {}
      },
      "onShownDateChange": {
        "isRequired": function () {}
      },
      "preventSnapRefocus": {
        "isRequired": function () {}
      },
      "preview": {
        "isRequired": function () {}
      },
      "rangeColors": {
        "isRequired": function () {}
      },
      "ranges": {
        "isRequired": function () {}
      },
      "retainEndDateOnFirstSelection": {
        "isRequired": function () {}
      },
      "scroll": {
        "isRequired": function () {}
      },
      "showDateDisplay": {
        "isRequired": function () {}
      },
      "showMonthAndYearPickers": {
        "isRequired": function () {}
      },
      "showMonthArrow": {
        "isRequired": function () {}
      },
      "showPreview": {
        "isRequired": function () {}
      },
      "shownDate": {
        "isRequired": function () {}
      },
      "startDatePlaceholder": {
        "isRequired": function () {}
      },
      "updateRange": {
        "isRequired": function () {}
      },
      "weekStartsOn": {
        "isRequired": function () {}
      },
      "weekdayDisplayFormat": {
        "isRequired": function () {}
      }
    }
  },
  "DateRangePicker": {
    "defaultProps": {},
    "propTypes": {
      "ariaLabels": {
        "isRequired": function () {}
      },
      "calendarFocus": {
        "isRequired": function () {}
      },
      "className": {
        "isRequired": function () {}
      },
      "classNames": {
        "isRequired": function () {}
      },
      "color": {
        "isRequired": function () {}
      },
      "date": {
        "isRequired": function () {}
      },
      "dateDisplayFormat": {
        "isRequired": function () {}
      },
      "dayDisplayFormat": {
        "isRequired": function () {}
      },
      "direction": {
        "isRequired": function () {}
      },
      "disabledDates": {
        "isRequired": function () {}
      },
      "disabledDay": {
        "isRequired": function () {}
      },
      "displayMode": {
        "isRequired": function () {}
      },
      "dragSelectionEnabled": {
        "isRequired": function () {}
      },
      "editableDateInputs": {
        "isRequired": function () {}
      },
      "endDatePlaceholder": {
        "isRequired": function () {}
      },
      "fixedHeight": {
        "isRequired": function () {}
      },
      "focusedRange": {
        "isRequired": function () {}
      },
      "footerContent": {
        "isRequired": function () {}
      },
      "headerContent": {
        "isRequired": function () {}
      },
      "initialFocusedRange": {
        "isRequired": function () {}
      },
      "inputRanges": {
        "isRequired": function () {}
      },
      "locale": {
        "isRequired": function () {}
      },
      "maxDate": {
        "isRequired": function () {}
      },
      "minDate": {
        "isRequired": function () {}
      },
      "monthDisplayFormat": {
        "isRequired": function () {}
      },
      "months": {
        "isRequired": function () {}
      },
      "moveRangeOnFirstSelection": {
        "isRequired": function () {}
      },
      "navigatorRenderer": {
        "isRequired": function () {}
      },
      "onChange": {
        "isRequired": function () {}
      },
      "onPreviewChange": {
        "isRequired": function () {}
      },
      "onRangeFocusChange": {
        "isRequired": function () {}
      },
      "onShownDateChange": {
        "isRequired": function () {}
      },
      "preventSnapRefocus": {
        "isRequired": function () {}
      },
      "preview": {
        "isRequired": function () {}
      },
      "rangeColors": {
        "isRequired": function () {}
      },
      "ranges": {
        "isRequired": function () {}
      },
      "renderStaticRangeLabel": {
        "isRequired": function () {}
      },
      "retainEndDateOnFirstSelection": {
        "isRequired": function () {}
      },
      "scroll": {
        "isRequired": function () {}
      },
      "showDateDisplay": {
        "isRequired": function () {}
      },
      "showMonthAndYearPickers": {
        "isRequired": function () {}
      },
      "showMonthArrow": {
        "isRequired": function () {}
      },
      "showPreview": {
        "isRequired": function () {}
      },
      "shownDate": {
        "isRequired": function () {}
      },
      "startDatePlaceholder": {
        "isRequired": function () {}
      },
      "staticRanges": {
        "isRequired": function () {}
      },
      "updateRange": {
        "isRequired": function () {}
      },
      "weekStartsOn": {
        "isRequired": function () {}
      },
      "weekdayDisplayFormat": {
        "isRequired": function () {}
      }
    }
  },
  "DefinedRange": {
    "defaultProps": {
      "focusedRange": {},
      "inputRanges": {},
      "rangeColors": {},
      "ranges": {},
      "staticRanges": {}
    },
    "propTypes": {
      "className": {
        "isRequired": function () {}
      },
      "focusedRange": {
        "isRequired": function () {}
      },
      "footerContent": {
        "isRequired": function () {}
      },
      "headerContent": {
        "isRequired": function () {}
      },
      "inputRanges": {
        "isRequired": function () {}
      },
      "onChange": {
        "isRequired": function () {}
      },
      "onPreviewChange": {
        "isRequired": function () {}
      },
      "rangeColors": {
        "isRequired": function () {}
      },
      "ranges": {
        "isRequired": function () {}
      },
      "renderStaticRangeLabel": {
        "isRequired": function () {}
      },
      "staticRanges": {
        "isRequired": function () {}
      }
    }
  },
  "createStaticRanges": function () {},
  "defaultInputRanges": {},
  "defaultStaticRanges": {}
};
ReactDateRange.Calendar.prototype = {
  "forceUpdate": function () {},
  "isPureReactComponent": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactDateRange.DateRange.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactDateRange.DateRangePicker.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactDateRange.DefinedRange.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
/**********************************************************************
 * End Generated Extern for ReactDateRange
/**********************************************************************/
